//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.20 at 11:48:52 AM BST 
//


package org.iso10383;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MIC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OPERATING_x0020_MIC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OPRT_x002F_SGMT" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="243"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MARKET_x0020_NAME-INSTITUTION_x0020_DESCRIPTION" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LEGAL_x0020_ENTITY_x0020_NAME" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LEI" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MARKET_x0020_CATEGORY_x0020_CODE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ACRONYM" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ISO_x0020_COUNTRY_x0020_CODE_x0020__x0028_ISO_x0020_3166_x0029_" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CITY" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WEBSITE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="STATUS" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CREATION_x0020_DATE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LAST_x0020_UPDATE_x0020_DATE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LAST_x0020_VALIDATION_x0020_DATE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EXPIRY_x0020_DATE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="COMMENTS" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mic",
    "operatingx0020MIC",
    "oprtx002FSGMT",
    "marketx0020NAMEINSTITUTIONX0020DESCRIPTION",
    "legalx0020ENTITYX0020NAME",
    "lei",
    "marketx0020CATEGORYX0020CODE",
    "acronym",
    "isox0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029",
    "city",
    "website",
    "status",
    "creationx0020DATE",
    "lastx0020UPDATEX0020DATE",
    "lastx0020VALIDATIONX0020DATE",
    "expiryx0020DATE",
    "comments"
})
@XmlRootElement(name = "ISO10383_MIC")
public class ISO10383MIC {

    @XmlElement(name = "MIC")
    protected String mic;
    @XmlElement(name = "OPERATING_x0020_MIC")
    protected String operatingx0020MIC;
    @XmlElement(name = "OPRT_x002F_SGMT")
    protected String oprtx002FSGMT;
    @XmlElement(name = "MARKET_x0020_NAME-INSTITUTION_x0020_DESCRIPTION")
    protected String marketx0020NAMEINSTITUTIONX0020DESCRIPTION;
    @XmlElement(name = "LEGAL_x0020_ENTITY_x0020_NAME")
    protected String legalx0020ENTITYX0020NAME;
    @XmlElement(name = "LEI")
    protected String lei;
    @XmlElement(name = "MARKET_x0020_CATEGORY_x0020_CODE")
    protected String marketx0020CATEGORYX0020CODE;
    @XmlElement(name = "ACRONYM")
    protected String acronym;
    @XmlElement(name = "ISO_x0020_COUNTRY_x0020_CODE_x0020__x0028_ISO_x0020_3166_x0029_")
    protected String isox0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029;
    @XmlElement(name = "CITY")
    protected String city;
    @XmlElement(name = "WEBSITE")
    protected String website;
    @XmlElement(name = "STATUS")
    protected String status;
    @XmlElement(name = "CREATION_x0020_DATE")
    protected String creationx0020DATE;
    @XmlElement(name = "LAST_x0020_UPDATE_x0020_DATE")
    protected String lastx0020UPDATEX0020DATE;
    @XmlElement(name = "LAST_x0020_VALIDATION_x0020_DATE")
    protected String lastx0020VALIDATIONX0020DATE;
    @XmlElement(name = "EXPIRY_x0020_DATE")
    protected String expiryx0020DATE;
    @XmlElement(name = "COMMENTS")
    protected String comments;

    /**
     * Gets the value of the mic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIC() {
        return mic;
    }

    /**
     * Sets the value of the mic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIC(String value) {
        this.mic = value;
    }

    /**
     * Gets the value of the operatingx0020MIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPERATINGX0020MIC() {
        return operatingx0020MIC;
    }

    /**
     * Sets the value of the operatingx0020MIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPERATINGX0020MIC(String value) {
        this.operatingx0020MIC = value;
    }

    /**
     * Gets the value of the oprtx002FSGMT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPRTX002FSGMT() {
        return oprtx002FSGMT;
    }

    /**
     * Sets the value of the oprtx002FSGMT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPRTX002FSGMT(String value) {
        this.oprtx002FSGMT = value;
    }

    /**
     * Gets the value of the marketx0020NAMEINSTITUTIONX0020DESCRIPTION property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARKETX0020NAMEINSTITUTIONX0020DESCRIPTION() {
        return marketx0020NAMEINSTITUTIONX0020DESCRIPTION;
    }

    /**
     * Sets the value of the marketx0020NAMEINSTITUTIONX0020DESCRIPTION property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARKETX0020NAMEINSTITUTIONX0020DESCRIPTION(String value) {
        this.marketx0020NAMEINSTITUTIONX0020DESCRIPTION = value;
    }

    /**
     * Gets the value of the legalx0020ENTITYX0020NAME property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEGALX0020ENTITYX0020NAME() {
        return legalx0020ENTITYX0020NAME;
    }

    /**
     * Sets the value of the legalx0020ENTITYX0020NAME property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEGALX0020ENTITYX0020NAME(String value) {
        this.legalx0020ENTITYX0020NAME = value;
    }

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the marketx0020CATEGORYX0020CODE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARKETX0020CATEGORYX0020CODE() {
        return marketx0020CATEGORYX0020CODE;
    }

    /**
     * Sets the value of the marketx0020CATEGORYX0020CODE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARKETX0020CATEGORYX0020CODE(String value) {
        this.marketx0020CATEGORYX0020CODE = value;
    }

    /**
     * Gets the value of the acronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACRONYM() {
        return acronym;
    }

    /**
     * Sets the value of the acronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACRONYM(String value) {
        this.acronym = value;
    }

    /**
     * Gets the value of the isox0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISOX0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029() {
        return isox0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029;
    }

    /**
     * Sets the value of the isox0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISOX0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029(String value) {
        this.isox0020COUNTRYX0020CODEX0020X0028ISOX00203166X0029 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITY(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEBSITE() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEBSITE(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the creationx0020DATE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONX0020DATE() {
        return creationx0020DATE;
    }

    /**
     * Sets the value of the creationx0020DATE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONX0020DATE(String value) {
        this.creationx0020DATE = value;
    }

    /**
     * Gets the value of the lastx0020UPDATEX0020DATE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTX0020UPDATEX0020DATE() {
        return lastx0020UPDATEX0020DATE;
    }

    /**
     * Sets the value of the lastx0020UPDATEX0020DATE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTX0020UPDATEX0020DATE(String value) {
        this.lastx0020UPDATEX0020DATE = value;
    }

    /**
     * Gets the value of the lastx0020VALIDATIONX0020DATE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTX0020VALIDATIONX0020DATE() {
        return lastx0020VALIDATIONX0020DATE;
    }

    /**
     * Sets the value of the lastx0020VALIDATIONX0020DATE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTX0020VALIDATIONX0020DATE(String value) {
        this.lastx0020VALIDATIONX0020DATE = value;
    }

    /**
     * Gets the value of the expiryx0020DATE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPIRYX0020DATE() {
        return expiryx0020DATE;
    }

    /**
     * Sets the value of the expiryx0020DATE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPIRYX0020DATE(String value) {
        this.expiryx0020DATE = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMENTS() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMENTS(String value) {
        this.comments = value;
    }

}
